export enum AuditAction {
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE",
  DELETE = "DELETE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  REGISTER = "REGISTER",
  AUTH_FAILED = "AUTH_FAILED",
  SYSTEM_EVENT = "SYSTEM_EVENT",
  BATCH_PROCESSING = "BATCH_PROCESSING",
  PACKAGING = "PACKAGING",
  SHIPPING = "SHIPPING",
  HARVEST = "HARVEST",
  PROCESSING = "PROCESSING"
}