export enum ServiceType {
  AUTH = "AUTH",
  USERS = "USERS",
  PRODUCTION = "PRODUCTION",
  PROCESSING = "PROCESSING",
  STORAGE = "STORAGE",
  SALES = "SALES",
  ANALYTICS = "ANALYTICS",
  PERFORMANCE = "PERFORMANCE",
  AUDIT = "AUDIT",
  GATEWAY = "GATEWAY"
}