export enum PerfumeType {
  FLORAL = "FLORAL",
  WOODY = "WOODY",
  FRESH = "FRESH",
  ORIENTAL = "ORIENTAL",
  CITRUS = "CITRUS",
  GOURMAND = "GOURMAND",
  AQUATIC = "AQUATIC",
  CHYPRE = "CHYPRE",
  FOUGERE = "FOUGERE",
  MUSK = "MUSK",
  SPICY = "SPICY",
  HERBAL = "HERBAL"
}