-- ============================================
-- CREATING ALL DATABASES FOR PERFUMERY
-- ============================================

-- 1. DATABASE FOR USERS (Auth + User)
CREATE DATABASE IF NOT EXISTS users_db;

-- 2. DATABASE FOR AUDIT LOGS  
CREATE DATABASE IF NOT EXISTS audit_logs;

-- 3. DATABASE FOR PRODUCTION
CREATE DATABASE IF NOT EXISTS production_db;

-- 4. DATABASE FOR PROCESSING
CREATE DATABASE IF NOT EXISTS processing_db;

-- 5. DATABASE FOR PACKAGING
CREATE DATABASE IF NOT EXISTS packaging_db;

-- 6. DATABASE FOR STORAGE
CREATE DATABASE IF NOT EXISTS storage_db;

-- 7. DATABASE FOR SALES
CREATE DATABASE IF NOT EXISTS sales_db;

-- 8. DATABASE FOR ANALYTICS
CREATE DATABASE IF NOT EXISTS analytics_reports;

-- 9. DATABASE FOR PERFORMANCE
CREATE DATABASE IF NOT EXISTS performance_reports;

-- Show all databases
SHOW DATABASES;