export enum ProductionEventType {
  PLANTING = "PLANTING",
  OIL_INTENSITY_CHANGE = "OIL_INTENSITY_CHANGE",
  HARVEST = "HARVEST",
  OIL_INTENSITY_GENERATION = "OIL_INTENSITY_GENERATION",
  ERROR = "ERROR",
  INFO = "INFO"
}