export enum AuditAction {
  // Sistem akcije
  SYSTEM_EVENT = "SYSTEM_EVENT",
  
  // Auth akcije
  LOGIN_ATTEMPT = "LOGIN_ATTEMPT",
  LOGIN_SUCCESS = "LOGIN_SUCCESS", 
  LOGIN_FAILED = "LOGIN_FAILED",
  LOGOUT = "LOGOUT",
  
  // Register akcije
  REGISTER_ATTEMPT = "REGISTER_ATTEMPT",
  REGISTER_SUCCESS = "REGISTER_SUCCESS",
  REGISTER_FAILED = "REGISTER_FAILED",

  REGISTER_VALIDATION_FAILED = "REGISTER_VALIDATION_FAILED",
  LOGIN_VALIDATION_FAILED = "LOGIN_VALIDATION_FAILED",
  
  // CRUD akcije
  CREATE = "CREATE",
  READ = "READ",
  UPDATE = "UPDATE", 
  DELETE = "DELETE",
  
  // Production akcije - osnovne
  PLANTING = "PLANTING",
  HARVEST = "HARVEST",
  OIL_INTENSITY_CHANGE = "OIL_INTENSITY_CHANGE",
  
  // Production akcije - detaljne
  CREATE_PLANT_STARTED = "CREATE_PLANT_STARTED",
  CREATE_PLANT_SUCCESS = "CREATE_PLANT_SUCCESS",
  CREATE_PLANT_FAILED = "CREATE_PLANT_FAILED",
  
  GET_ALL_PLANTS = "GET_ALL_PLANTS",
  GET_ALL_PLANTS_SUCCESS = "GET_ALL_PLANTS_SUCCESS",
  GET_ALL_PLANTS_FAILED = "GET_ALL_PLANTS_FAILED",
  
  GET_PLANT_BY_ID = "GET_PLANT_BY_ID",
  GET_PLANT_BY_ID_SUCCESS = "GET_PLANT_BY_ID_SUCCESS",
  GET_PLANT_BY_ID_NOT_FOUND = "GET_PLANT_BY_ID_NOT_FOUND",
  GET_PLANT_BY_ID_FAILED = "GET_PLANT_BY_ID_FAILED",
  
  CHANGE_OIL_INTENSITY_STARTED = "CHANGE_OIL_INTENSITY_STARTED",
  CHANGE_OIL_INTENSITY_SUCCESS = "CHANGE_OIL_INTENSITY_SUCCESS",
  CHANGE_OIL_INTENSITY_FAILED = "CHANGE_OIL_INTENSITY_FAILED",
  CHANGE_OIL_INTENSITY_PLANT_NOT_FOUND = "CHANGE_OIL_INTENSITY_PLANT_NOT_FOUND",
  
  OIL_INTENSITY_THRESHOLD_EXCEEDED = "OIL_INTENSITY_THRESHOLD_EXCEEDED",
  
  HARVEST_PLANTS_STARTED = "HARVEST_PLANTS_STARTED",
  HARVEST_PLANTS_SUCCESS = "HARVEST_PLANTS_SUCCESS",
  HARVEST_PLANTS_FAILED = "HARVEST_PLANTS_FAILED",
  HARVEST_PLANTS_CANNOT_HARVEST = "HARVEST_PLANTS_CANNOT_HARVEST",
  
  GET_PLANTS_FOR_PROCESSING = "GET_PLANTS_FOR_PROCESSING",
  GET_PLANTS_FOR_PROCESSING_SUCCESS = "GET_PLANTS_FOR_PROCESSING_SUCCESS",
  GET_PLANTS_FOR_PROCESSING_FAILED = "GET_PLANTS_FOR_PROCESSING_FAILED",
  
  GET_AVAILABLE_PLANTS = "GET_AVAILABLE_PLANTS",
  GET_AVAILABLE_PLANTS_SUCCESS = "GET_AVAILABLE_PLANTS_SUCCESS",
  GET_AVAILABLE_PLANTS_FAILED = "GET_AVAILABLE_PLANTS_FAILED",
  
  GET_PRODUCTION_LOGS = "GET_PRODUCTION_LOGS",
  GET_PRODUCTION_LOGS_SUCCESS = "GET_PRODUCTION_LOGS_SUCCESS",
  GET_PRODUCTION_LOGS_FAILED = "GET_PRODUCTION_LOGS_FAILED",
  
  GET_LOGS_BY_PLANT_ID = "GET_LOGS_BY_PLANT_ID",
  GET_LOGS_BY_PLANT_ID_SUCCESS = "GET_LOGS_BY_PLANT_ID_SUCCESS",
  GET_LOGS_BY_PLANTS_ID_FAILED = "GET_LOGS_BY_PLANTS_ID_FAILED",
  
  REQUEST_NEW_PLANT_STARTED = "REQUEST_NEW_PLANT_STARTED",
  REQUEST_NEW_PLANT_SUCCESS = "REQUEST_NEW_PLANT_SUCCESS",
  REQUEST_NEW_PLANT_FAILED = "REQUEST_NEW_PLANT_FAILED",
  REQUEST_NEW_PLANT_PLANT_NOT_FOUND = "REQUEST_NEW_PLANT_PLANT_NOT_FOUND",
  
  GENERATE_RANDOM_OIL_INTENSITY = "GENERATE_RANDOM_OIL_INTENSITY",
  
  // Processing akcije
  PROCESSING_START = "PROCESSING_START",
  PROCESSING_COMPLETE = "PROCESSING_COMPLETE",
  PROCESSING_FAILED = "PROCESSING_FAILED"
}