export enum ServiceType {
  AUTH = "AUTH",
  USER = "USER",
  PRODUCTION = "PRODUCTION",
  PROCESSING = "PROCESSING",
  PACKAGING = "PACKAGING",
  SALES = "SALES",
  INVENTORY = "INVENTORY",
  AUDIT = "AUDIT",
  GATEWAY = "GATEWAY"
}