export enum ServiceType {
  PRODUCTION = "PRODUCTION",
  PROCESSING = "PROCESSING",
  STORAGE = "STORAGE",
  SALES = "SALES",
  ANALYTICS = "ANALYTICS",
  PERFORMANCE = "PERFORMANCE",
  AUTH = "AUTH",
  USER = "USER",
  AUDIT = "AUDIT",
  GATEWAY = "GATEWAY",
}
